clients: fix bug where files were marked removed when second mount on same client fails

diff --git a/test_tools/mount b/test_tools/mount
--- a/test_tools/mount
+++ b/test_tools/mount
@@ -42,6 +42,11 @@ shift
 dest="$1"
 shift
 
+# See if told to fail (nfs)
+if [ -r "$src/fail" ]; then
+  exit 1
+fi
+
 # Simulate mounting of share
 rm -rf "$dest"
 cp -a "$src" "$dest"
