tests: cosmetic change

diff --git a/cli/test/hbackup_test b/cli/test/hbackup_test
--- a/cli/test/hbackup_test
+++ b/cli/test/hbackup_test
@@ -54,7 +54,8 @@ echo "Restore all data in a prefix" >> $output
 rm -rf test_r && ../hbackup -d -c etc/hbackup.conf -r test_r -C file://myhost >> $output 2>&1
 
 # Check
-if ! diff -q $expected $output; then
+if ! diff -q $expected $output > /dev/null; then
+	echo "$target: error: test output is different from expected" >&2
 	exit 3
 fi
 
diff --git a/test_tools/test_run b/test_tools/test_run
--- a/test_tools/test_run
+++ b/test_tools/test_run
@@ -23,7 +23,8 @@ if ! ./$executable > $output 2>&1; then
 fi
 
 # Check
-if ! diff -q $expected $output; then
+if ! diff -q $expected $output > /dev/null; then
+	echo "$target: error: test output is different from expected" >&2
 	exit 3
 fi
 
